rm -r *_output
script_path='/home/akrotz/Research/pyMQC/'
echo 'Testing Holstein lattice Mean-Field '
python $script_path/main.py holstein_lattice_input_MF '{"address":"auto"}'
echo 'Testing Holstein Fewest-Switches Surface Hopping Deterministic '
python $script_path/main.py holstein_lattice_input_FSSH_deterministic '{"address":"auto"}'
echo 'Testing Holstein Fewest-Switches Surface Hopping Stochastic '
python $script_path/main.py holstein_lattice_input_FSSH_stochastic '{"address":"auto"}'
echo 'Testing Holstein lattice Coherent Fewest-Switches Surface Hopping Deterministic '
python $script_path/main.py holstein_lattice_input_CFSSH_deterministic '{"address":"auto"}'
echo 'Testing Holstein lattice Coherent Fewest-Switches Surface Hopping Stochastic '
python $script_path/main.py holstein_lattice_input_CFSSH_stochastic '{"address":"auto"}'