script_path='/home/akrotz/Research/pyMQC/'
echo 'Testing Holstein lattice Mean-Field '
python $script_path/main.py holstein_lattice_input_MF '{"address":"auto"}'
echo 'Testing Holstein Fewest-Switches Surface Hopping Deterministic '
python /home/akrotz/Research/pyMQC/main.py holstein_lattice_input_FSSH_deterministic '{"address":"auto"}'
echo 'Testing Holstein Fewest-Switches Surface Hopping Stochastic '
python /home/akrotz/Research/pyMQC/main.py holstein_lattice_input_FSSH_stochastic '{"address":"auto"}'
echo 'Testing Holstein lattice Coherent Fewest-Switches Surface Hopping '
python /home/akrotz/Research/pyMQC/main.py holstein_lattice_input_CFSSH '{"address":"auto"}'
